services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    volumes:
      - mongodb:/data/db
  
  book-api:
    build: .
    ports: 
      - 3000:3000
    environment:
      DM_API_ROOT: /api
      DM_BASE_URL: http://localhost:3000/
      DM_BOOKS_DB_URL: mongodb://admin:password@mongodb:27017
      DM_BOOKS_DB_NAME: dm_books_api
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo-db: {}

